// dsh-skins 聚合脚本：扫 skins/*/skin.json，生成 build/index.js + build/registry.json。
//
// 入口模式：
//   node scripts/aggregate.mjs          // 生成 build/
//   node scripts/aggregate.mjs --check  // 校验 build/ 与源码一致（CI 门禁）
//
// 生成的 build/ 是「单文件聚合」：用 import 引入每款皮肤的 skin.json 元数据，
// 再调 register() 一次性塞进共享注册表。生产环境只要装这一个包就够了。

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..');  // 仓库根
const PKG = resolve(__dirname, '..');          // dsh-skins/
const SKINS_DIR = join(ROOT, 'skins');
const BUILD_DIR = join(PKG, 'build');
const INDEX_OUT = join(BUILD_DIR, 'index.js');
const REGISTRY_OUT = join(BUILD_DIR, 'registry.json');

const checkMode = process.argv.includes('--check');

// [1] 扫 skins/*/skin.json（排除 skin-center 自己，它是注册表不是皮肤）
const skinDirs = readdirSync(SKINS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory() && e.name !== 'skin-center')
  .map((e) => e.name)
  .sort();

const metas = [];
for (const id of skinDirs) {
  const skinJson = join(SKINS_DIR, id, 'skin.json');
  if (!existsSync(skinJson)) {
    throw new Error(`missing skin.json in skins/${id}`);
  }
  const meta = JSON.parse(readFileSync(skinJson, 'utf8'));
  if (meta.id !== id) {
    throw new Error(`skin id mismatch: dir=${id} json=${meta.id}`);
  }
  metas.push(meta);
}

console.log(`[aggregate] found ${metas.length} skin(s): ${metas.map((m) => m.id).join(', ')}`);

// [2] 生成 build/registry.json（人读 + 工具读）
const registry = {
  version: 1,
  generated: new Date().toISOString(),
  count: metas.length,
  skins: metas,
};

// [3] 生成 build/index.js —— ES module，一次性 import + register
const indexJs = `// AUTO-GENERATED by scripts/aggregate.mjs — DO NOT EDIT
// 6 款极简 editorial 原创皮肤聚合入口。import 这一个文件即注册全部 6 款到 @dsh-desktop/shared。
// 重新生成：node scripts/aggregate.mjs

import { register } from '@dsh-desktop/shared';
${metas.map((m, i) => `import __skin${i} from '@dsh-desktop/skin-${m.id}/skin.json' with { type: 'json' };`).join('\n')}

const __disposers = [
${metas.map((_, i) => `  register(__skin${i}),`).join('\n')}
];

export const skins = [
${metas.map((_, i) => `  __skin${i},`).join('\n')}
];

export function dispose() {
  for (const d of __disposers) d();
  __disposers.length = 0;
}

export default { skins, dispose };
`;

if (checkMode) {
  // 校验模式：与磁盘上 build/ 对比
  if (!existsSync(INDEX_OUT) || !existsSync(REGISTRY_OUT)) {
    throw new Error('build/ missing; run `pnpm --filter @dsh-desktop/skins-all build` first');
  }
  const cur = JSON.parse(readFileSync(REGISTRY_OUT, 'utf8'));
  if (cur.count !== registry.count || cur.skins.length !== registry.skins.length) {
    throw new Error(`registry count mismatch: file=${cur.count} src=${registry.count}`);
  }
  for (let i = 0; i < metas.length; i++) {
    if (cur.skins[i].id !== metas[i].id) {
      throw new Error(`registry[${i}].id mismatch: file=${cur.skins[i].id} src=${metas[i].id}`);
    }
  }
  const curIndex = readFileSync(INDEX_OUT, 'utf8');
  if (curIndex !== indexJs) {
    throw new Error('build/index.js out of date; run `pnpm --filter @dsh-desktop/skins-all build`');
  }
  console.log('[aggregate] CHECK OK — build/ is in sync with skins/');
  process.exit(0);
}

// 写入模式
import { mkdirSync } from 'node:fs';
mkdirSync(BUILD_DIR, { recursive: true });
writeFileSync(REGISTRY_OUT, JSON.stringify(registry, null, 2) + '\n', 'utf8');
writeFileSync(INDEX_OUT, indexJs, 'utf8');
console.log(`[aggregate] wrote build/registry.json (${metas.length} skins)`);
console.log(`[aggregate] wrote build/index.js (${indexJs.length} bytes)`);
